### ISSUE TITLE
Could you provide a licence for this code

### ISSUE THREAD

**Issue by svyotov** [muayyad-alsadi/pyredis-dump#1]
I am interested in reusing this code, but without any licence provided such a use is not possible.
If it is not an inconvenience, would it be possible for you to provide a licence for the project?

**Comment by muayyad-alsadi** [comment]
do you suggest any? is GPLv2 good for you?

**Comment by svyotov** [comment]
What would suit me best would be Apache License 2.0, however this is your project and your code so it is completely up to you. I just would love to have something specific in order to decide whether I can use it or not.
Thank you very much for the quick response!

**Comment by svyotov** [comment]
@muayyad-alsadi what is your response regarding the licence? 
Thank you!

**Comment by muayyad-alsadi** [comment]
added GPLv2
